urls:
  - tgram://2125345483:AAGrMdK4E8ID1GCuzNp0HhY1IvEGrS8sPTU/1193275356
  # - discord://WebhookID/WebhookToken/
  # - slack://tokenA/tokenB/tokenC
  # More options here: https://github.com/caronc/apprise
